version: "3.5"

services:

  api:
    depends_on:
      - mongo
    environment:
      DEBUG: api.mygram.svc.com:*
    container_name: api
    volumes:
      - .:/usr/src/api
    stdin_open: true
    tty: true
    ports:
      - "${PORT}:${PORT}"
    working_dir: /usr/src/api
    image: node:8.15-alpine
    command: npm start

  mongo:
    container_name: db
    image: mongo
    ports:
      - "27017:27017"